In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df =pd.read_csv("/content/Airplane_Crashes_and_Fatalities_Since_1908_20190820105639.csv")
df.head()

,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn/ln,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground,Summary
0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,1.0,1.0,1.0,0.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,09/07/1909,NaN,"Juvisy-sur-Orge, France",NaN,NaN,Air show,Wright Byplane,SC1,NaN,1.0,0.0,1.0,1.0,0.0,0.0,0.0,Eugene Lefebvre was the first pilot to ever be...
2,07/12/1912,06:30,"Atlantic City, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,0.0,5.0,5.0,0.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
3,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,NaN,NaN,Curtiss seaplane,NaN,NaN,1.0,0.0,1.0,1.0,0.0,1.0,0.0,The first fatal airplane accident in Canada oc...
4,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,NaN,NaN,14.0,NaN,NaN,0.0,The airship flew into a thunderstorm and encou...

In [ ]:
df.tail()

,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn/ln,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground,Summary
3289,12/19/1984,14:00,"Near Jaen, Peru",Military - Fuerza Aérea del Peru,NaN,NaN,de Havilland Canada DHC-6 Twin Otter 300,FAP-307,317,21.0,18.0,3.0,21.0,18.0,3.0,0.0,"Crashed in flames, two minutes after taking of..."
3290,12/22/1984,NaN,"Near Bhojpur, Nepal",Royal Nepal Airlines,NaN,Katmandou-Bhojpur,de Havilland Canada DHC-6 Twin Otter 300,9N-ABH,376,23.0,20.0,3.0,15.0,12.0,3.0,0.0,Crashed into mountain in poor weather off the ...
3291,12/23/1984,14:15,"Near Kranoyarsk, Russia",Aeroflot,3519,Krasnoyarsk - Irkutsk,Tupolev TU-154B-2,CCCP-85338,338,111.0,104.0,7.0,110.0,103.0,7.0,0.0,The aircraft crashed while attempting an emerg...
3292,01/01/1985,20:30,"Near La Paz, Bolivia",Eastern Air Lines,980,"Asuncion, Paraguay - La Paz, Bolivia",Boeing B-727-225 Adv,N819EA,22556/1793,29.0,19.0,10.0,29.0,19.0,10.0,0.0,The aircraft hit Mt. Illimani at an altitude o...
3293,01/09/1985,07:00,"Kansas City, Kansas",TPI International Airways,NaN,Detroit - Kansas City,Lockheed L-188AF Electra,N357Q,1044,3.0,0.0,3.0,3.0,0.0,3.0,0.0,The cargo plane executed a missed approach bec...

In [ ]:
df.isnull()

,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn/ln,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground,Summary
0,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False
1,False,True,False,True,True,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,True,True,False,False,False,False,False,False,False,False
3,False,True,False,False,True,True,False,True,True,False,False,False,False,False,False,False,False
4,False,False,False,False,True,True,False,True,True,False,True,True,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3289,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False
3290,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
3291,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3292,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3293,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().any()

Date                     False
Time                      True
Location                  True
Operator                  True
Flight #                  True
Route                     True
AC Type                   True
Registration              True
cn/ln                     True
Aboard                    True
Aboard Passangers         True
Aboard Crew               True
Fatalities                True
Fatalities Passangers     True
Fatalities Crew           True
Ground                    True
Summary                   True
dtype: bool

In [ ]:
df.isnull().sum()

Date                        0
Time                     1168
Location                    4
Operator                    9
Flight #                 2529
Route                     592
AC Type                    13
Registration              183
cn/ln                     522
Aboard                     16
Aboard Passangers         171
Aboard Crew               167
Fatalities                  8
Fatalities Passangers     175
Fatalities Crew           174
Ground                     38
Summary                    55
dtype: int64

In [ ]:
df.isnull().sum()

Date                        0
Time                     1168
Location                    4
Operator                    9
Flight #                 2529
Route                     592
AC Type                    13
Registration              183
cn/ln                     522
Aboard                     16
Aboard Passangers         171
Aboard Crew               167
Fatalities                  8
Fatalities Passangers     175
Fatalities Crew           174
Ground                     38
Summary                    55
dtype: int64

In [ ]:
df.['Location']

In [ ]:
df['time'].mode([0])

KeyError: ignored